### ISSUE TITLE
HITLIST COUNTER

### ISSUE THREAD

**Issue by ramblingadam** [ramblingadam/100devs-mvc-auth-huntober-group#5]
- A counter with buttons user can press to track the number of companies they've completed the hitlist for.
- Data must be stored in DB using a DIFFERENT model than the Todos model.
- **TASK**: Make the buttons.
- **TASK**: Make the buttons update data in DB.
- **TASK**: Get the hitlist counter data from DB for each render, add to EJS
 - **QUESTION**: Should we store this data right on the User Scheme or make a new Schema to hold only this info? I would lean toward just storing it on the User. Thoughts?
 - **QUESTION**: Where do you guys think this should go on the page? Maybe above the todos list?

Please add a COMMENT with your thoughts on the hitlist counter, or to claim this issue for you to work on.

**Comment by racheleckenrod** [comment]
Alright, I am going for this task, wish me luck!!

**Comment by racheleckenrod** [comment]
success! Thank you Adam!
